/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Dropdown from 'src/components/Dropdown/Dropdown';
import Dropdown1 from 'src/components/Dropdown1/Dropdown1';
import Dropdown2 from 'src/components/Dropdown2/Dropdown2';
import Dropdown3 from 'src/components/Dropdown3/Dropdown3';
import DropdownVariant4 from 'src/components/DropdownVariant4/DropdownVariant4';

const Frame31 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 0.75)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `856px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Dropdown4 = styled(Dropdown)(({ theme }) => ({
  width: `85px`,
  height: `28px`,
  position: `absolute`,
  left: `151px`,
  top: `42px`,
}));

const Dropdown11 = styled(Dropdown1)(({ theme }) => ({
  width: `79px`,
  height: `27px`,
  position: `absolute`,
  left: `280px`,
  top: `42px`,
}));

const Dropdown21 = styled(Dropdown2)(({ theme }) => ({
  width: `79px`,
  height: `27px`,
  position: `absolute`,
  left: `410px`,
  top: `42px`,
}));

const Dropdown31 = styled(Dropdown3)(({ theme }) => ({
  width: `85px`,
  height: `28px`,
  position: `absolute`,
  left: `522px`,
  top: `45px`,
}));

const DropdownVariant41 = styled(DropdownVariant4)(({ theme }) => ({
  width: `79px`,
  height: `27px`,
  position: `absolute`,
  left: `39px`,
  top: `42px`,
}));

function Frame3(props) {
  return (
    <Frame31 className={props.className}>
      <Dropdown4 />
      <Dropdown11 />
      <Dropdown21 />
      <Dropdown31 />
      <DropdownVariant41 />
    </Frame31>
  );
}

export default Frame3;
