/**********************************************************************
 *
 *   Responsiveness hook generated by Quest
 *
 *   Responsive Logic for the component goes in this hook
 *   If you want to customize the min/max values for the breakpoints, open the component on Quest Editor.
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

const useAuthentication2ResponsiveSize = () => {
  const [variant, setVariant] = React.useState('ScreenDesktop');

  React.useEffect(() => {
    const handlerScreenScreen2 = (e) =>
      setVariant((size) => (e.matches ? 'ScreenScreen2' : size));

    const ScreenScreen2Size = window.matchMedia('(max-width: 908px)');
    setVariant((size) => (ScreenScreen2Size.matches ? 'ScreenScreen2' : size));
    ScreenScreen2Size.addEventListener('change', handlerScreenScreen2);

    const handlerScreenDesktop = (e) =>
      setVariant((size) => (e.matches ? 'ScreenDesktop' : size));

    const ScreenDesktopSize = window.matchMedia('(min-width: 909px)');
    setVariant((size) => (ScreenDesktopSize.matches ? 'ScreenDesktop' : size));
    ScreenDesktopSize.addEventListener('change', handlerScreenDesktop);
  }, []);

  return variant;
};

export default useAuthentication2ResponsiveSize;
