/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import XpectoImage from 'src/assets/images/Frame4_XPECTO.png';
import AchievementsImage from 'src/assets/images/Frame4_ACHIEVEMENTS.png';
import AboutImage from 'src/assets/images/Frame4_ABOUT.png';
import ServicesImage from 'src/assets/images/Frame4_SERVICES.png';
import ContactImage from 'src/assets/images/Frame4_CONTACT.png';
import MaskGroupImage from 'src/assets/images/Frame4_Mask_group.png';
import VectorImage from 'src/assets/images/Frame4_Vector.png';
import Vector1Image from 'src/assets/images/Frame4_Vector_1.png';
import Vector2Image from 'src/assets/images/Frame4_Vector_2.png';
import Vector3Image from 'src/assets/images/Frame4_Vector_3.png';
import Vector4Image from 'src/assets/images/Frame4_Vector_4.png';
import Vector5Image from 'src/assets/images/Frame4_Vector_5.png';
import Vector6Image from 'src/assets/images/Frame4_Vector_6.png';
import Vector7Image from 'src/assets/images/Frame4_Vector_7.png';
import Vector8Image from 'src/assets/images/Frame4_Vector_8.png';
import Vector9Image from 'src/assets/images/Frame4_Vector_9.png';
import Vector10Image from 'src/assets/images/Frame4_Vector_10.png';
import Ellipse1Image from 'src/assets/images/Frame4_Ellipse_1.png';
import Ellipse2Image from 'src/assets/images/Frame4_Ellipse_2.png';
import Ellipse3Image from 'src/assets/images/Frame4_Ellipse_3.png';
import Vector11Image from 'src/assets/images/Frame4_Vector_11.png';
import Vector12Image from 'src/assets/images/Frame4_Vector_12.png';
import Vector13Image from 'src/assets/images/Frame4_Vector_13.png';
import Vector14Image from 'src/assets/images/Frame4_Vector_14.png';
import { styled } from '@mui/material/styles';
import Frame4 from 'src/components/Frame4/Frame4';

const Frame42 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `719px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame43 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.1)`,
  boxSizing: `border-box`,
  borderRadius: `2px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `479px`,
  height: `672px`,
  left: `13px`,
  top: `15px`,
  overflow: `hidden`,
});

const Rectangle8 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  borderRadius: `0px`,
  width: `479px`,
  height: `32px`,
  position: `absolute`,
  left: `0px`,
  top: `640px`,
});

const Rectangle7 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 0.01)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `0px`,
  width: `142px`,
  height: `207px`,
  position: `absolute`,
  left: `326px`,
  top: `386px`,
});

const Rectangle6 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `0px`,
  width: `142px`,
  height: `207px`,
  position: `absolute`,
  left: `166px`,
  top: `386px`,
});

const Rectangle5 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `0px`,
  width: `142px`,
  height: `207px`,
  position: `absolute`,
  left: `10px`,
  top: `386px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(69, 60, 60, 1)`,
  borderRadius: `0px`,
  width: `451px`,
  height: `132px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const IndianInstituteOfTec = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Jacques Francois Shadow`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `92px`,
  top: `82px`,
});

const Xpecto = styled('img')({
  height: `15px`,
  width: `48px`,
  position: `absolute`,
  left: `40px`,
  top: `31px`,
});

const Achievements = styled('img')({
  height: `15px`,
  width: `94px`,
  position: `absolute`,
  left: `116px`,
  top: `31px`,
});

const About = styled('img')({
  height: `15px`,
  width: `42px`,
  position: `absolute`,
  left: `224px`,
  top: `31px`,
});

const Services = styled('img')({
  height: `15px`,
  width: `58px`,
  position: `absolute`,
  left: `286px`,
  top: `31px`,
});

const Contact = styled('img')({
  height: `15px`,
  width: `58px`,
  position: `absolute`,
  left: `364px`,
  top: `31px`,
});

const AboutUs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `53px`,
  height: `21px`,
  position: `absolute`,
  left: `199px`,
  top: `151px`,
});

const Frame = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `25px`,
  left: `213px`,
  top: `172px`,
});

const MaskGroup = styled('img')({
  height: `25px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const KamandPrompt = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `78px`,
  height: `13px`,
  position: `absolute`,
  left: `190px`,
  top: `206px`,
});

const Vector = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `105px`,
  top: `222px`,
});

const Vector1 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `154px`,
  top: `222px`,
});

const Vector2 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `192px`,
  top: `222px`,
});

const Frame1 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `18px`,
  left: `229px`,
  top: `222px`,
  overflow: `hidden`,
});

const Vector3 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector4 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `272px`,
  top: `222px`,
});

const Vector5 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `319px`,
  top: `222px`,
});

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `48px`,
  top: `256px`,
});

const Vector6 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `355px`,
  top: `222px`,
});

const Vector7 = styled('img')({
  height: `17.44px`,
  width: `18px`,
  position: `absolute`,
  left: `114px`,
  top: `186px`,
});

const Vector8 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `31px`,
  top: `154px`,
});

const Vector9 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `306px`,
  top: `185px`,
});

const Vector10 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `393px`,
  top: `154px`,
});

const TheTeam = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `65px`,
  height: `19px`,
  position: `absolute`,
  left: `199px`,
  top: `350px`,
});

const Ellipse1 = styled('img')({
  height: `76px`,
  width: `76px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `34px`,
  top: `408px`,
});

const Ellipse2 = styled('img')({
  height: `76px`,
  width: `76px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `202px`,
  top: `408px`,
});

const Ellipse3 = styled('img')({
  height: `76px`,
  width: `76px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `353px`,
  top: `408px`,
});

const JashwanthMummalaneniSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneniSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gotu`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneniSpan3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const JashwanthMummalaneniSpan4 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `132px`,
  position: `absolute`,
  left: `15px`,
  top: `510px`,
});

const JashwanthMummalaneni1Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni1Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gotu`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni1Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const JashwanthMummalaneni1Span4 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `132px`,
  position: `absolute`,
  left: `170px`,
  top: `510px`,
});

const JashwanthMummalaneni2Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni2Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gotu`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni2Span3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const JashwanthMummalaneni2Span4 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const JashwanthMummalaneni2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `132px`,
  position: `absolute`,
  left: `330px`,
  top: `510px`,
});

const Q2023AndelaAllRightsSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Q2023AndelaAllRightsSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const Q2023AndelaAllRightsSpan3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Q2023AndelaAllRights = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `112px`,
  position: `absolute`,
  left: `4px`,
  top: `649px`,
});

const BuiltOnQualifiedIoSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const BuiltOnQualifiedIoSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const BuiltOnQualifiedIo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `123px`,
  top: `649px`,
});

const Api = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `188px`,
  top: `649px`,
});

const PrivacyPolicy = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `211px`,
  top: `649px`,
});

const TermsOfService = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `261px`,
  top: `649px`,
});

const About1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TharLon`,
  fontWeight: `400`,
  fontSize: `7px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `323px`,
  top: `649px`,
});

const Vector11 = styled('img')({
  height: `9px`,
  width: `10px`,
  position: `absolute`,
  left: `375px`,
  top: `650px`,
});

const Vector12 = styled('img')({
  height: `8px`,
  width: `12px`,
  position: `absolute`,
  left: `397px`,
  top: `650px`,
});

const Vector13 = styled('img')({
  height: `9px`,
  width: `11px`,
  position: `absolute`,
  left: `421px`,
  top: `650px`,
});

const Vector14 = styled('img')({
  height: `7px`,
  width: `12px`,
  position: `absolute`,
  left: `442px`,
  top: `651px`,
});

const Frame44 = styled(Frame4)(({ theme }) => ({
  width: `479px`,
  height: `672px`,
  position: `absolute`,
  left: `534px`,
  top: `15px`,
}));

const Frame45 = styled(Frame4)(({ theme }) => ({
  width: `479px`,
  height: `672px`,
  position: `absolute`,
  left: `1055px`,
  top: `15px`,
}));

function Frame41(props) {
  return (
    <Frame42 className={props.className}>
      <Frame43>
        <Rectangle8></Rectangle8>
        <Rectangle7></Rectangle7>
        <Rectangle6></Rectangle6>
        <Rectangle5></Rectangle5>
        <Rectangle1></Rectangle1>
        <IndianInstituteOfTec>
          {`Indian Institute of Technology Mandi`}
        </IndianInstituteOfTec>
        <Xpecto src={XpectoImage} loading="lazy" alt={'XPECTO'} />
        <Achievements
          src={AchievementsImage}
          loading="lazy"
          alt={'ACHIEVEMENTS'}
        />
        <About src={AboutImage} loading="lazy" alt={'ABOUT'} />
        <Services src={ServicesImage} loading="lazy" alt={'SERVICES'} />
        <Contact src={ContactImage} loading="lazy" alt={'CONTACT'} />
        <AboutUs>{`About Us`}</AboutUs>
        <Frame>
          <MaskGroup src={MaskGroupImage} loading="lazy" alt={'Mask group'} />
        </Frame>
        <KamandPrompt>{`Kamand Prompt`}</KamandPrompt>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
        <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
        <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
        <Frame1>
          <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
        </Frame1>
        <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
        <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
        <LoremIpsumDolorSitAm>
          {`Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rerum
 repellendus voluptate saepe illum vitae itaque quaerat aut a
 minus iste ut maxime, debitis laboriosam laborum modi 
accusamus necessitatibus mollitia similique.`}
        </LoremIpsumDolorSitAm>
        <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
        <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
        <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
        <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
        <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
        <TheTeam>{`The Team`}</TheTeam>
        <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
        <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
        <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
        <JashwanthMummalaneni>
          <JashwanthMummalaneniSpan1>{`Jashwanth Mummalaneni
`}</JashwanthMummalaneniSpan1>
          <JashwanthMummalaneniSpan2>{`General Secretary
Technical Board
`}</JashwanthMummalaneniSpan2>
          <JashwanthMummalaneniSpan3>{`linkedin
`}</JashwanthMummalaneniSpan3>
          <JashwanthMummalaneniSpan4>{`Webmail: techsec@iitg.ac.in`}</JashwanthMummalaneniSpan4>
        </JashwanthMummalaneni>
        <JashwanthMummalaneni1>
          <JashwanthMummalaneni1Span1>{`Jashwanth Mummalaneni
`}</JashwanthMummalaneni1Span1>
          <JashwanthMummalaneni1Span2>{`General Secretary
Technical Board
`}</JashwanthMummalaneni1Span2>
          <JashwanthMummalaneni1Span3>{`linkedin
`}</JashwanthMummalaneni1Span3>
          <JashwanthMummalaneni1Span4>{`Webmail: techsec@iitg.ac.in`}</JashwanthMummalaneni1Span4>
        </JashwanthMummalaneni1>
        <JashwanthMummalaneni2>
          <JashwanthMummalaneni2Span1>{`Jashwanth Mummalaneni
`}</JashwanthMummalaneni2Span1>
          <JashwanthMummalaneni2Span2>{`General Secretary
Technical Board
`}</JashwanthMummalaneni2Span2>
          <JashwanthMummalaneni2Span3>{`linkedin
`}</JashwanthMummalaneni2Span3>
          <JashwanthMummalaneni2Span4>{`Webmail: techsec@iitg.ac.in`}</JashwanthMummalaneni2Span4>
        </JashwanthMummalaneni2>
        <Q2023AndelaAllRights>
          <Q2023AndelaAllRightsSpan1>{`© 2023 `}</Q2023AndelaAllRightsSpan1>
          <Q2023AndelaAllRightsSpan2>{`Andela`}</Q2023AndelaAllRightsSpan2>
          <Q2023AndelaAllRightsSpan3>{`. All rights reserved.`}</Q2023AndelaAllRightsSpan3>
        </Q2023AndelaAllRights>
        <BuiltOnQualifiedIo>
          <BuiltOnQualifiedIoSpan1>{`Built on `}</BuiltOnQualifiedIoSpan1>
          <BuiltOnQualifiedIoSpan2>{`Qualified.io`}</BuiltOnQualifiedIoSpan2>
        </BuiltOnQualifiedIo>
        <Api>{`API`}</Api>
        <PrivacyPolicy>{`Privacy Policy`}</PrivacyPolicy>
        <TermsOfService>{`Terms of Service`}</TermsOfService>
        <About1>{`About`}</About1>
        <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
        <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
        <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
        <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
      </Frame43>
      <Frame44 />
      <Frame45 />
    </Frame42>
  );
}

export default Frame41;
