/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Download1Image from 'src/assets/images/Desktop1_download_1.png';
import Download2Image from 'src/assets/images/Desktop1_download_2.png';
import Download3Image from 'src/assets/images/Desktop1_download_3.png';
import VectorImage from 'src/assets/images/Desktop1_Vector.png';
import Vector1Image from 'src/assets/images/Desktop1_Vector_1.png';
import Vector2Image from 'src/assets/images/Desktop1_Vector_2.png';
import Logo2Image from 'src/assets/images/Desktop1_logo_2.png';
import Vector3Image from 'src/assets/images/Desktop1_Vector_3.png';
import Vector4Image from 'src/assets/images/Desktop1_Vector_4.png';
import Vector5Image from 'src/assets/images/Desktop1_Vector_5.png';
import Logo1Image from 'src/assets/images/Desktop1_logo_1.png';
import Vector6Image from 'src/assets/images/Desktop1_Vector_6.png';
import Vector7Image from 'src/assets/images/Desktop1_Vector_7.png';
import Vector8Image from 'src/assets/images/Desktop1_Vector_8.png';
import Vector9Image from 'src/assets/images/Desktop1_Vector_9.png';
import Vector10Image from 'src/assets/images/Desktop1_Vector_10.png';
import Vector11Image from 'src/assets/images/Desktop1_Vector_11.png';
import Vector12Image from 'src/assets/images/Desktop1_Vector_12.png';
import { styled } from '@mui/material/styles';
import FrameImage from 'src/assets/images/Desktop1_Frame.png';

const Desktop11 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `4733px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Projects = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `50px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `810px`,
  top: `3549px`,
});

const Frame11 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `121px`,
  top: `3690px`,
});

const Download1 = styled('img')({
  height: `275px`,
  width: `413px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Download2 = styled('img')({
  height: `275px`,
  width: `413px`,
  objectFit: `cover`,
  margin: `0px 0px 0px 167px`,
});

const Download3 = styled('img')({
  height: `275px`,
  width: `413px`,
  objectFit: `cover`,
  margin: `0px 0px 0px 167px`,
});

const Frame = styled('div')({
  backgroundImage: `url(${FrameImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1814px`,
  height: `568px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const StreamlineInterfaceS = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `49px`,
  height: `49px`,
  left: `1346px`,
  top: `27px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `35px`,
  width: `45.5px`,
  position: `absolute`,
  left: `2px`,
  top: `7px`,
});

const SolarDoubleAltArrowD = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `36px`,
  height: `28.5px`,
  left: `889px`,
  top: `471px`,
  overflow: `hidden`,
});

const Group = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21px`,
  height: `11.87px`,
  left: `8px`,
  top: `8px`,
});

const Vector1 = styled('img')({
  height: `7.13px`,
  width: `21px`,
  position: `absolute`,
  left: `0px`,
  top: `5px`,
});

const Vector2 = styled('img')({
  height: `7.13px`,
  width: `21px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const LearnMore = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `848px`,
  top: `511px`,
});

const Logo2 = styled('img')({
  height: `60px`,
  width: `150px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `49px`,
  top: `51px`,
});

const Frame1 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1674px`,
  height: `124px`,
  left: `49px`,
  top: `871px`,
  overflow: `hidden`,
});

const FastWeStriveForFastMSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const FastWeStriveForFastMSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const FastWeStriveForFastM = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `62px`,
  top: `24px`,
});

const AccurateWeAreTheGodfSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const AccurateWeAreTheGodfSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const AccurateWeAreTheGodf = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `351px`,
  position: `absolute`,
  left: `653px`,
  top: `13px`,
});

const ReadyToHelpWeAreAlwaSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const ReadyToHelpWeAreAlwaSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const ReadyToHelpWeAreAlwa = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `397px`,
  position: `absolute`,
  left: `1277px`,
  top: `0px`,
});

const Vector3 = styled('img')({
  height: `105.86px`,
  width: `44.09px`,
  position: `absolute`,
  left: `0px`,
  top: `18px`,
});

const Vector4 = styled('img')({
  height: `52.87px`,
  width: `34px`,
  position: `absolute`,
  left: `1222px`,
  top: `26px`,
});

const CarbonGrowth = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `70px`,
  height: `70px`,
  left: `567px`,
  top: `16px`,
  overflow: `hidden`,
});

const Vector5 = styled('img')({
  height: `39.38px`,
  width: `61.25px`,
  position: `absolute`,
  left: `4px`,
  top: `17px`,
});

const Frame2 = styled('div')({
  backgroundColor: `rgba(242, 242, 242, 1)`,
  borderRadius: `90px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `423px`,
  height: `132px`,
  left: `702px`,
  top: `1678px`,
  overflow: `hidden`,
});

const LearnMore1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `38px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `83px`,
  top: `43px`,
});

const Frame3 = styled('div')({
  backgroundColor: `rgba(69, 60, 60, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1814px`,
  height: `682px`,
  left: `0px`,
  top: `4029px`,
  overflow: `hidden`,
});

const Home = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `67px`,
  top: `74px`,
});

const Facebook = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `305px`,
  top: `74px`,
});

const Team = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `67px`,
  top: `145px`,
});

const Github = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `305px`,
  top: `145px`,
});

const Events = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `66px`,
  top: `215px`,
});

const Logo1 = styled('img')({
  height: `60px`,
  width: `150px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `50px`,
  top: `569px`,
});

const Line6 = styled('div')({
  border: `1px solid rgba(152, 146, 146, 1)`,
  width: `1814px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `505px`,
});

const HeuristicsIntegralPaSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const HeuristicsIntegralPaSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const HeuristicsIntegralPaSpan3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const HeuristicsIntegralPaSpan4 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const HeuristicsIntegralPaSpan5 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const HeuristicsIntegralPa = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `926px`,
  top: `530px`,
});

const Vector6 = styled('img')({
  height: `26.4px`,
  width: `32.41px`,
  position: `absolute`,
  left: `1488px`,
  top: `606px`,
});

const Vector7 = styled('img')({
  height: `24px`,
  width: `32px`,
  position: `absolute`,
  left: `1617px`,
  top: `608px`,
});

const Vector8 = styled('img')({
  height: `28px`,
  width: `14.7px`,
  position: `absolute`,
  left: `1563px`,
  top: `604px`,
});

const OiArrowCircleTop = styled('div')({
  backgroundColor: `rgba(146, 232, 238, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `72px`,
  height: `72px`,
  left: `1712px`,
  top: `579px`,
  overflow: `hidden`,
});

const Vector9 = styled('img')({
  height: `72px`,
  width: `72px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame4 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1706px`,
  height: `157px`,
  left: `24px`,
  top: `1018px`,
  overflow: `hidden`,
});

const Frame5 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1291px`,
  height: `128px`,
  left: `0px`,
  top: `29px`,
  overflow: `hidden`,
});

const EndlessPossibilitiesSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const EndlessPossibilitiesSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const EndlessPossibilities = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `338px`,
  height: `126px`,
  position: `absolute`,
  left: `87px`,
  top: `2px`,
});

const PowerfulPerformanceWSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const PowerfulPerformanceWSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const PowerfulPerformanceW = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `368px`,
  position: `absolute`,
  left: `672px`,
  top: `0px`,
});

const Vector10 = styled('img')({
  height: `94.24px`,
  width: `67px`,
  position: `absolute`,
  left: `0px`,
  top: `18px`,
});

const Vector11 = styled('img')({
  height: `81.6px`,
  width: `64px`,
  position: `absolute`,
  left: `586px`,
  top: `17px`,
});

const Vector12 = styled('img')({
  height: `72.41px`,
  width: `70px`,
  position: `absolute`,
  left: `1221px`,
  top: `17px`,
});

const FamilyWeAreJustAFamiSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const FamilyWeAreJustAFamiSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const FamilyWeAreJustAFami = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `373px`,
  position: `absolute`,
  left: `1333px`,
  top: `0px`,
});

const Frame6 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1090px`,
  height: `715px`,
  left: `88px`,
  top: `2075px`,
  overflow: `hidden`,
});

const Frame7 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `331px`,
  height: `295px`,
  left: `0px`,
  top: `81px`,
  overflow: `hidden`,
});

const AboutHeuristics = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Culture = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(146, 232, 238, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `23px`,
});

const AtHeuristicsWeFocusO = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `464px`,
  height: `715px`,
  position: `absolute`,
  left: `626px`,
  top: `0px`,
});

const Frame8 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1032px`,
  height: `24px`,
  left: `0px`,
  top: `626px`,
  overflow: `hidden`,
});

const WelcomeToHeuristics = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(79, 209, 202, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `774px`,
  top: `0px`,
});

const Frame9 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1114px`,
  height: `51px`,
  left: `0px`,
  top: `734px`,
  overflow: `hidden`,
});

const WeCreateTheFuture = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `42px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `680px`,
  top: `0px`,
});

const Frame10 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1384px`,
  height: `170px`,
  left: `0px`,
  top: `1360px`,
  overflow: `hidden`,
});

const OurParentClubKamandP = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `498px`,
  top: `0px`,
});

const Line2 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  width: `1814px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `1269px`,
});

const Line3 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  width: `1814px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `1991px`,
});

const Line4 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  width: `1814px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `2865px`,
});

const Frame12 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1536px`,
  height: `290px`,
  left: `0px`,
  top: `3057px`,
  overflow: `hidden`,
});

const CompetitionsAndChallSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `60px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const CompetitionsAndChallSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const CompetitionsAndChall = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `1136px`,
  height: `290px`,
  position: `absolute`,
  left: `400px`,
  top: `0px`,
});

const Line5 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  width: `1814px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `3510px`,
});

function Desktop1(props) {
  return (
    <Desktop11 className={props.className}>
      <Projects>{`Projects`}</Projects>
      <Frame11>
        <Download1 src={Download1Image} loading="lazy" alt={'download 1'} />
        <Download2 src={Download2Image} loading="lazy" alt={'download 2'} />
        <Download3 src={Download3Image} loading="lazy" alt={'download 3'} />
      </Frame11>
      <Frame>
        <StreamlineInterfaceS>
          <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
        </StreamlineInterfaceS>
        <SolarDoubleAltArrowD>
          <Group>
            <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
            <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
          </Group>
        </SolarDoubleAltArrowD>
        <LearnMore>{`LEARN MORE`}</LearnMore>
        <Logo2 src={Logo2Image} loading="lazy" alt={'logo 2'} />
      </Frame>
      <Frame1>
        <FastWeStriveForFastM>
          <FastWeStriveForFastMSpan1>{`Fast
`}</FastWeStriveForFastMSpan1>
          <FastWeStriveForFastMSpan2>{`We strive for fast models`}</FastWeStriveForFastMSpan2>
        </FastWeStriveForFastM>
        <AccurateWeAreTheGodf>
          <AccurateWeAreTheGodfSpan1>{`Accurate
`}</AccurateWeAreTheGodfSpan1>
          <AccurateWeAreTheGodfSpan2>{`We are the godfathers of accuracy.`}</AccurateWeAreTheGodfSpan2>
        </AccurateWeAreTheGodf>
        <ReadyToHelpWeAreAlwa>
          <ReadyToHelpWeAreAlwaSpan1>{`Ready To Help
`}</ReadyToHelpWeAreAlwaSpan1>
          <ReadyToHelpWeAreAlwaSpan2>{`We are always ready to help each other and grow together`}</ReadyToHelpWeAreAlwaSpan2>
        </ReadyToHelpWeAreAlwa>
        <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
        <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
        <CarbonGrowth>
          <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
        </CarbonGrowth>
      </Frame1>
      <Frame2>
        <LearnMore1>{`LEARN MORE`}</LearnMore1>
      </Frame2>
      <Frame3>
        <Home>{`HOME`}</Home>
        <Facebook>{`FACEBOOK`}</Facebook>
        <Team>{`TEAM`}</Team>
        <Github>{`GITHUB`}</Github>
        <Events>{`EVENTS`}</Events>
        <Logo1 src={Logo1Image} loading="lazy" alt={'logo 1'} />
        <Line6></Line6>
        <HeuristicsIntegralPa>
          <HeuristicsIntegralPaSpan1>{`Heuristics, `}</HeuristicsIntegralPaSpan1>
          <HeuristicsIntegralPaSpan2>{`Integral part of: `}</HeuristicsIntegralPaSpan2>
          <HeuristicsIntegralPaSpan3>{`KamandPrompt`}</HeuristicsIntegralPaSpan3>
          <HeuristicsIntegralPaSpan4>{` - `}</HeuristicsIntegralPaSpan4>
          <HeuristicsIntegralPaSpan5>{`IIT Mandi`}</HeuristicsIntegralPaSpan5>
        </HeuristicsIntegralPa>
        <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
        <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
        <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
        <OiArrowCircleTop>
          <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
        </OiArrowCircleTop>
      </Frame3>
      <Frame4>
        <Frame5>
          <EndlessPossibilities>
            <EndlessPossibilitiesSpan1>{`Endless Possibilities
`}</EndlessPossibilitiesSpan1>
            <EndlessPossibilitiesSpan2>{`This is the place where you have endless possibilities of success.`}</EndlessPossibilitiesSpan2>
          </EndlessPossibilities>
          <PowerfulPerformanceW>
            <PowerfulPerformanceWSpan1>{`Powerful Performance
`}</PowerfulPerformanceWSpan1>
            <PowerfulPerformanceWSpan2>{`We always look for powerful performance 
from our members.`}</PowerfulPerformanceWSpan2>
          </PowerfulPerformanceW>
          <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
          <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
          <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
        </Frame5>
        <FamilyWeAreJustAFami>
          <FamilyWeAreJustAFamiSpan1>{`Family
`}</FamilyWeAreJustAFamiSpan1>
          <FamilyWeAreJustAFamiSpan2>{`We are just a family who vibe with AI.`}</FamilyWeAreJustAFamiSpan2>
        </FamilyWeAreJustAFami>
      </Frame4>
      <Frame6>
        <Frame7>
          <AboutHeuristics>
            {`
About
Heuristics`}
          </AboutHeuristics>
          <Culture>{`CULTURE`}</Culture>
        </Frame7>
        <AtHeuristicsWeFocusO>
          {`At Heuristics we focus on enhancing the culture of Data Science, Machine Learning at IIT Mandi. It also expands to solve complex optimization problems. It underlies the whole field of Artificial  Intelligence and the computer simulation of thinking, as they may be used in situations where there are no known algorithms. We organize regular events, challenges and workshops on the above mentioned topics.`}
        </AtHeuristicsWeFocusO>
      </Frame6>
      <Frame8>
        <WelcomeToHeuristics>{`WELCOME TO HEURISTICS`}</WelcomeToHeuristics>
      </Frame8>
      <Frame9>
        <WeCreateTheFuture>{`We Create The Future`}</WeCreateTheFuture>
      </Frame9>
      <Frame10>
        <OurParentClubKamandP>
          {`Our Parent Club :
KamandPrompt - IIT Mandi`}
        </OurParentClubKamandP>
      </Frame10>
      <Line2></Line2>
      <Line3></Line3>
      <Line4></Line4>
      <Frame12>
        <CompetitionsAndChall>
          <CompetitionsAndChallSpan1>{`COMPETITIONS AND CHALLENGES
`}</CompetitionsAndChallSpan1>
          <CompetitionsAndChallSpan2>{`We Often Organise Machine Learning Competitions, Hacking Competitions And Other Interesting Challenges For Our Community And Strongly Encourage Students To Participate And Learn`}</CompetitionsAndChallSpan2>
        </CompetitionsAndChall>
      </Frame12>
      <Line5></Line5>
    </Desktop11>
  );
}

export default Desktop1;
