/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ShopNavbar1 from 'src/components/ShopNavbar1/ShopNavbar1';
import ProductPage1 from 'src/components/ProductPage1/ProductPage1';
import ShoppingFooter1 from 'src/components/ShoppingFooter1/ShoppingFooter1';
import useLayoutProductPage1 from 'src/components/LayoutProductPage1/useLayoutProductPage1';

const ScreenDesktop = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
});

const ShopNavbar11 = styled(ShopNavbar1, {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ theme, data }) => ({
  alignSelf: `stretch`,
  height:
    data.currentVariant === 'ScreenTablet'
      ? `50px`
      : data.currentVariant === 'ScreenMobile'
      ? 'unset'
      : `48px`,
  margin: `0px`,
}));

const ProductPage11 = styled(ProductPage1)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `10px 0px 0px 0px`,
}));

const ShoppingFooter11 = styled(ShoppingFooter1)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `10px 0px 0px 0px`,
}));

function LayoutProductPage1(props) {
  const { data } = useLayoutProductPage1();

  return (
    <ScreenDesktop className={props.className}>
      <ShopNavbar11 data={data} />
      <ProductPage11 />
      <ShoppingFooter11 />
    </ScreenDesktop>
  );
}

export default LayoutProductPage1;
